[Ram] Modifies to add javadoc comments
anantjain6/ProductManagementSystem pull request #19
Opened 2020-10-02 20:52 UTC by ramgsuri

Modifies to add javadoc comments in Product Controller , Order Controller, ProductCategory Controller and all domain models

2020-10-03 15:22 UTC, anantjain6 commented
Patch for #2

2020-10-04 12:35 UTC, ramgsuri commented
Hi @anantjain6 let me know if any review comments otherwise please close the PR.

2020-10-04 13:39 UTC, anantjain6 commented
@ramgsuri First of all thanks for your contribution

Sorry for the late response

I have added review comments on code changes

Also, I have following comments:-

1.  Comments are missing at "HomeController"
2.  Comments are missing at "viewMyOrder" method of "OrderController"
3.  Comments are missing at "OrderProduct" Model

Your suggestions are also welcome

2020-10-04 18:43 UTC, ramgsuri commented
Review Comments Incorporated #19

2020-10-05 17:53 UTC, anantjain6 requested changes

2020-10-05 19:30 UTC, ramgsuri commented on src/main/java/me/anant/PMS/controller/OrderController.java
> +	 * @return
Done

2020-10-05 19:30 UTC, ramgsuri commented on src/main/java/me/anant/PMS/controller/ProductController.java
> +	 * @return
Done

2020-10-06 17:31 UTC, anantjain6 approved these changes

2020-10-06 17:56 UTC, ramgsuri commented
hi @anantjain6 can you merge the PR and please close this PR.

2020-10-06 18:16 UTC, anantjain6 commented
@ramgsuri It solves the issue perfectly

Can you add a commit for deleting "EmailConfig" class?

Actually, the remote master branch has been updated due to which it is creating conflict. I can still push your codes by resolving conflict but in that way, I'll not able to maintain full credit of your work.

If you add commit for deleting EmailConfig class then your pull request can be merged smoothly with full credits of your work.

2020-10-06 18:27 UTC, ramgsuri commented
Ohh ok Thanks a lot, thats the reason I was wondering, what's missing here 👍

2020-10-06 18:31 UTC, ramgsuri commented
Hi @anantjain6 then this would also require delete in EmailService would that be ok as it is Autowirred in EmailService ?

2020-10-06 18:32 UTC, anantjain6 commented
@ramgsuri EmailService will get auto-merged. No action required for that

2020-10-06 18:39 UTC, ramgsuri commented
Done

2020-10-06 18:41 UTC, merged